import type { MentorData } from "../../types";

export const MENTOR_DATA: MentorData[] = [
  {
    _id: "67624fccd5f5cffe13a68889",
    mentorName: "Karthick Balaraman",
    profilePicture: "https://i.ibb.co/D1D241r/Karthik.jpg",
    designation: "CEO, Managing Director",
    linkedIn: "https://www.linkedin.com/in/karthikbalaraman/",
    index: 1,
    experience: 15,
    skills: [
      { skill: "Leadership", area: "Management" },
      { skill: "Business Strategy", area: "Entrepreneurship" },
      { skill: "Agile", area: "Project Management" },
      { skill: "Scrum", area: "Project Management" },
    ],
  },
  {
    _id: "67624fccd5f5cffe13a6888a",
    mentorName: "Brindha Karthick",
    profilePicture: "https://i.ibb.co/tKBMPKc/Brindha.jpg",
    designation: "Technical Lead",
    linkedIn: "https://www.linkedin.com/in/brindakarthik/",
    index: 2,
    experience: 10,
    skills: [
      { skill: "JavaScript", area: "Frontend Development" },
      { skill: "React", area: "Frontend Framework" },
      { skill: "Node.js", area: "Backend Development" },
      { skill: "System Design", area: "Architecture" },
    ],
  },
  {
    _id: "67624fccd5f5cffe13a6888b",
    mentorName: "Vijay Kumar",
    profilePicture: "https://i.ibb.co/g4V7Tmv/Vijay.jpg",
    designation: "Alumni",
    linkedIn: "https://www.linkedin.com/in/vijayakumarbhaskar/",
    index: 3,
    experience: 3,
    skills: [
      { skill: "Java", area: "Backend Development" },
      { skill: "Spring Boot", area: "Java Framework" },
      { skill: "SQL", area: "Database" },
    ],
  },
  {
    _id: "67624fccd5f5cffe13a6888c",
    mentorName: "Mohamed Ijass",
    profilePicture: "https://i.ibb.co/KxQ6rz8/Ijass.jpg",
    designation: "Developer / Sr.Trainer",
    linkedIn: "https://www.linkedin.com/in/mohamed-ijass-0891a12b0/",
    index: 4,
    experience: 8,
    skills: [
      { skill: "MongoDB", area: "Database" },
      { skill: "Express.js", area: "Backend Framework" },
      { skill: "React", area: "Frontend Framework" },
      { skill: "Node.js", area: "Backend Development" },
    ],
  },
  {
    _id: "67624fccd5f5cffe13a6888d",
    mentorName: "Anusuya Balakrishnan",
    profilePicture: "https://i.ibb.co/MnCVz85/anusuya.png",
    designation: "Developer / Trainer",
    linkedIn: "https://www.linkedin.com/in/anusuya-balakrishnan-260629230/",
    index: 5,
    experience: 6,
    skills: [
      { skill: "HTML", area: "Frontend Basics" },
      { skill: "CSS", area: "Styling" },
      { skill: "JavaScript", area: "Frontend Development" },
      { skill: "Bootstrap", area: "CSS Framework" },
    ],
  },
  {
    _id: "67624fccd5f5cffe13a6888e",
    mentorName: "Vidhya",
    profilePicture:
      "https://firebasestorage.googleapis.com/v0/b/oceanlivereact.appspot.com/o/trainerImage%2Fvidhya.jpeg?alt=media&token=1760a053-94fa-4415-8800-c1ddefcf0e81",
    designation: "Developer / Trainer",
    linkedIn: "https://www.linkedin.com/in/vidhya-v-970253214/",
    index: 6,
    experience: 5,
    skills: [
      { skill: "React", area: "Frontend Framework" },
      { skill: "Redux", area: "State Management" },
      { skill: "TypeScript", area: "Frontend Development" },
      { skill: "Firebase", area: "Backend as a Service" },
    ],
  },
  {
    _id: "67624fccd5f5cffe13a6888f",
    mentorName: "Maheshwaran",
    profilePicture:
      "https://firebasestorage.googleapis.com/v0/b/oceanlivereact.appspot.com/o/trainerImage%2Fmaheshwaran.jpg?alt=media&token=8a5919d1-2964-4b5f-ab35-1d89da23100c",
    designation: "Developer / Trainer",
    linkedIn: "https://www.linkedin.com/in/mahi14/",
    index: 7,
    experience: 4,
    skills: [
      { skill: "Flutter", area: "Mobile Development" },
      { skill: "Firebase", area: "Backend as a Service" },
      { skill: "Bloc", area: "State Management" },
      { skill: "Clean Architecture", area: "Software Design" },
      { skill: "Firebase", area: "Backend as a Service" },
      { skill: "Bloc", area: "State Management" },
      { skill: "Clean Architecture", area: "Software Design" },
    ],
  },
  {
    _id: "67624fccd5f5cffe13a68890",
    mentorName: "Jayashree",
    profilePicture:
      "https://firebasestorage.googleapis.com/v0/b/oceanlivereact.appspot.com/o/trainerImage%2Fjayashree.jpg?alt=media&token=16ccaf6b-23ac-4df4-bd5e-8e5a3f4826c1",
    designation: "Admin",
    linkedIn: "https://www.linkedin.com/in/jayshree-srima/",
    index: 8,
    experience: 7,
    skills: [
      { skill: "Team Coordination", area: "Operations" },
      { skill: "Scheduling", area: "Administrative Tasks" },
      { skill: "Documentation", area: "Office Management" },
    ],
  },
  {
    _id: "67624fccd5f5cffe13a68891",
    mentorName: "Sangeetha",
    profilePicture:
      "https://firebasestorage.googleapis.com/v0/b/oceanlivereact.appspot.com/o/trainerImage%2Fsangeetha.s.jpg?alt=media&token=9f6d316e-d9f2-41a2-a79c-724126a7e480",
    designation: "Developer / Trainer",
    linkedIn: "https://www.linkedin.com/in/sangeetha-s-02a0bb1b6/",
    index: 9,
    experience: 5,
    skills: [
      { skill: "Python", area: "Programming Language" },
      { skill: "Data Science", area: "Analytics" },
      { skill: "NumPy", area: "Scientific Computing" },
      { skill: "Pandas", area: "Data Analysis" },
    ],
  },
  {
    _id: "67624fccd5f5cffe13a68892",
    mentorName: "Bhadresh",
    profilePicture:
      "https://firebasestorage.googleapis.com/v0/b/oceanlivereact.appspot.com/o/trainerImage%2Fbhadresh.jpg?alt=media&token=97c0d015-1780-43d6-8d3a-dc86755d100d",
    designation: "Developer / Trainer",
    index: 10,
    linkedIn: "https://www.linkedin.com/in/bhadresh-p-bb426024b/",
    experience: 4,
    skills: [
      { skill: "Java", area: "Backend Development" },
      { skill: "Angular", area: "Frontend Framework" },
      { skill: "Node.js", area: "Backend Development" },
    ],
  },
  {
    _id: "67624fccd5f5cffe13a68896",
    mentorName: "Rajeswari",
    profilePicture:
      "https://firebasestorage.googleapis.com/v0/b/oceanlivereact.appspot.com/o/trainerImage%2Frajeswari.jpeg?alt=media&token=4440cb8e-8e61-4a54-a99e-cba9b424d21c",
    designation: "Developer / Trainer",
    linkedIn: "https://www.linkedin.com/in/raje-ammu-607bb0213/",
    index: 11,
    experience: 3,
    skills: [
      { skill: "HTML", area: "Frontend Basics" },
      { skill: "CSS", area: "Styling" },
      { skill: "JavaScript", area: "Frontend Development" },
    ],
  },
  {
    _id: "67624fccd5f5cffe13a68893",
    mentorName: "Alan Raj",
    profilePicture:
      "https://firebasestorage.googleapis.com/v0/b/oceanlivereact.appspot.com/o/trainerImage%2Falan.jpg?alt=media&token=3652f031-4f78-4b61-9ee8-d02a59cad5fc",
    designation: "Data Analyst",
    linkedIn: "https://www.linkedin.com/in/ealanraj/",
    index: 12,
    experience: 6,
    skills: [
      { skill: "Power BI", area: "Data Visualization" },
      { skill: "Excel", area: "Spreadsheets" },
      { skill: "SQL", area: "Database Querying" },
    ],
  },
  {
    _id: "67624fccd5f5cffe13a68894",
    mentorName: "Varadharaja Perumal",
    profilePicture:
      "https://firebasestorage.googleapis.com/v0/b/oceanlivereact.appspot.com/o/profiles%2FVaradharaja_Perumal.jpg?alt=media&token=da0957f3-4b86-4d85-a9fc-cd16eb5ee80d",
    designation: "Data Analyst",
    linkedIn: "https://www.linkedin.com/in/varadharaja-perumal-g/",
    index: 13,
    experience: 7,
    skills: [
      { skill: "Python", area: "Programming Language" },
      { skill: "Power BI", area: "Data Visualization" },
      { skill: "SQL", area: "Database Querying" },
      { skill: "Data Cleaning", area: "Analytics" },
    ],
  },
  {
    _id: "67624fccd5f5cffe13a68895",
    mentorName: "Aswin",
    profilePicture:
      "https://firebasestorage.googleapis.com/v0/b/oceanlivereact.appspot.com/o/trainerImage%2FAswin.jpg?alt=media&token=67c35d5d-bc98-4b25-bba8-831b85e64c07",
    designation: "Intern",
    linkedIn: "https://www.linkedin.com/in/aswin-g-91792a264/",
    index: 14,
    experience: 1,
    skills: [
      { skill: "HTML", area: "Frontend Basics" },
      { skill: "CSS", area: "Styling" },
      { skill: "Git", area: "Version Control" },
      { skill: "Figma", area: "UI/UX Design" },
    ],
  },
];
