[
  {
    courseId: 1,
    courseName: "Angular",
    courseIcon: "🅰️",
    courseImg: "https://example.com/angular-course.jpg",
    description:
      "Master Angular framework for building dynamic web applications with TypeScript, components, and modern development practices.",
    duration: "3-4 months",
    students: 15420,
    rating: 4.6,
    level: "Intermediate",
    price: "₹25,999",
    avgSalary: {
      fresher: "₹4.5 LPA",
      experienced: "₹12 LPA",
      average: "₹8.2 LPA",
    },
    availability: {
      online: true,
      offline: true,
      hybrid: true,
    },
    completionRate: 78,
    growthData: [
      { year: 2020, demand: 65, salary: 550000 },
      { year: 2021, demand: 72, salary: 620000 },
      { year: 2022, demand: 78, salary: 680000 },
      { year: 2023, demand: 85, salary: 750000 },
      { year: 2024, demand: 92, salary: 820000 },
    ],
    salaryByExperience: [
      { experience: "0-1 years", salary: 450000 },
      { experience: "1-3 years", salary: 650000 },
      { experience: "3-5 years", salary: 950000 },
      { experience: "5-8 years", salary: 1350000 },
      { experience: "8+ years", salary: 1800000 },
    ],
    careerPaths: [
      { title: "Frontend Developer", growth: "High", salary: "₹6-12 LPA" },
      { title: "Angular Developer", growth: "Very High", salary: "₹8-15 LPA" },
      { title: "Full Stack Developer", growth: "High", salary: "₹10-18 LPA" },
      { title: "Technical Lead", growth: "Medium", salary: "₹15-25 LPA" },
    ],
    whatYouLearn: [
      "Angular framework fundamentals",
      "TypeScript programming",
      "Component architecture",
      "Services and dependency injection",
      "Routing and navigation",
      "Form handling and validation",
      "HTTP client and API integration",
      "State management with NgRx",
      "Testing with Jasmine and Karma",
      "Deployment and optimization",
    ],
    courseFeatures: [
      "Live instructor-led sessions",
      "Hands-on projects",
      "Industry-relevant curriculum",
      "Career placement support",
      "Lifetime access to materials",
      "24/7 doubt resolution",
      "Mock interviews",
      "Certificate of completion",
    ],
    salaryStatistics: [
      {
        title: "Average Salary in India",
        lpa: "₹8.2 LPA",
        subtitle: "Based on current market data",
      },
      {
        title: "Top Earners (90th percentile)",
        lpa: "₹18+ LPA",
        subtitle: "Experienced professionals",
      },
      {
        title: "Entry Level Range",
        lpa: "₹4-6 LPA",
        subtitle: "Fresh graduates",
      },
    ],
    marketInsights: [
      {
        title: "Industry Size",
        content: "$89.6 billion",
        subtitle: "Expected market size by 2025",
      },
      {
        title: "Job Growth Rate",
        content: "22%",
        subtitle: "Faster than average growth",
      },
      {
        title: "Remote Work",
        content: "75%",
        subtitle: "Positions offer remote work",
      },
    ],
    hiringCompanies: [
      "Google",
      "Microsoft",
      "Accenture",
      "TCS",
      "Infosys",
      "Wipro",
      "IBM",
      "Capgemini",
      "HCL",
      "Tech Mahindra",
    ],
  },
  {
    courseId: 2,
    courseName: "C++",
    courseIcon: "⚡",
    courseImg: "https://example.com/cpp-course.jpg",
    description:
      "Learn C++ programming from basics to advanced concepts including OOP, STL, and system programming.",
    duration: "4-5 months",
    students: 18750,
    rating: 4.4,
    level: "Beginner to Advanced",
    price: "₹18,999",
    avgSalary: {
      fresher: "₹4 LPA",
      experienced: "₹15 LPA",
      average: "₹9.5 LPA",
    },
    availability: {
      online: true,
      offline: true,
      hybrid: true,
    },
    completionRate: 72,
    growthData: [
      { year: 2020, demand: 58, salary: 520000 },
      { year: 2021, demand: 62, salary: 580000 },
      { year: 2022, demand: 68, salary: 650000 },
      { year: 2023, demand: 75, salary: 720000 },
      { year: 2024, demand: 82, salary: 800000 },
    ],
    salaryByExperience: [
      { experience: "0-1 years", salary: 400000 },
      { experience: "1-3 years", salary: 600000 },
      { experience: "3-5 years", salary: 900000 },
      { experience: "5-8 years", salary: 1400000 },
      { experience: "8+ years", salary: 2000000 },
    ],
    careerPaths: [
      { title: "Software Developer", growth: "High", salary: "₹5-10 LPA" },
      { title: "System Programmer", growth: "Medium", salary: "₹8-15 LPA" },
      { title: "Game Developer", growth: "High", salary: "₹6-12 LPA" },
      { title: "Embedded Developer", growth: "Medium", salary: "₹7-14 LPA" },
    ],
    whatYouLearn: [
      "C++ syntax and fundamentals",
      "Object-oriented programming",
      "Memory management",
      "Standard Template Library (STL)",
      "File handling and I/O",
      "Exception handling",
      "Templates and generic programming",
      "Multithreading concepts",
      "Data structures and algorithms",
      "Performance optimization",
    ],
    courseFeatures: [
      "Comprehensive curriculum",
      "Practical coding exercises",
      "Real-world projects",
      "Expert instructor guidance",
      "Code review sessions",
      "Programming contests",
      "Industry case studies",
      "Career guidance",
    ],
    salaryStatistics: [
      {
        title: "Average Salary in India",
        lpa: "₹9.5 LPA",
        subtitle: "Based on current market data",
      },
      {
        title: "Top Earners (90th percentile)",
        lpa: "₹20+ LPA",
        subtitle: "Experienced professionals",
      },
      {
        title: "Entry Level Range",
        lpa: "₹3.5-5 LPA",
        subtitle: "Fresh graduates",
      },
    ],
    marketInsights: [
      {
        title: "Industry Size",
        content: "$75.2 billion",
        subtitle: "Expected market size by 2025",
      },
      {
        title: "Job Growth Rate",
        content: "19%",
        subtitle: "Faster than average growth",
      },
      {
        title: "Remote Work",
        content: "65%",
        subtitle: "Positions offer remote work",
      },
    ],
    hiringCompanies: [
      "Intel",
      "AMD",
      "NVIDIA",
      "Samsung",
      "Qualcomm",
      "Adobe",
      "Microsoft",
      "Google",
      "Amazon",
      "Oracle",
    ],
  },
  {
    courseId: 3,
    courseName: "C Programming",
    courseIcon: "🔷",
    courseImg: "https://example.com/c-course.jpg",
    description:
      "Master the fundamentals of C programming, the foundation of modern programming languages.",
    duration: "2-3 months",
    students: 22100,
    rating: 4.3,
    level: "Beginner",
    price: "₹12,999",
    avgSalary: {
      fresher: "₹3.5 LPA",
      experienced: "₹12 LPA",
      average: "₹7.8 LPA",
    },
    availability: {
      online: true,
      offline: true,
      hybrid: true,
    },
    completionRate: 85,
    growthData: [
      { year: 2020, demand: 55, salary: 480000 },
      { year: 2021, demand: 58, salary: 520000 },
      { year: 2022, demand: 62, salary: 580000 },
      { year: 2023, demand: 68, salary: 640000 },
      { year: 2024, demand: 75, salary: 720000 },
    ],
    salaryByExperience: [
      { experience: "0-1 years", salary: 350000 },
      { experience: "1-3 years", salary: 520000 },
      { experience: "3-5 years", salary: 780000 },
      { experience: "5-8 years", salary: 1200000 },
      { experience: "8+ years", salary: 1800000 },
    ],
    careerPaths: [
      { title: "System Programmer", growth: "Medium", salary: "₹5-12 LPA" },
      { title: "Embedded Developer", growth: "High", salary: "₹6-14 LPA" },
      { title: "Firmware Engineer", growth: "High", salary: "₹7-15 LPA" },
      { title: "Software Engineer", growth: "High", salary: "₹4-10 LPA" },
    ],
    whatYouLearn: [
      "C programming fundamentals",
      "Data types and variables",
      "Control structures",
      "Functions and modular programming",
      "Arrays and strings",
      "Pointers and memory management",
      "File handling",
      "Data structures implementation",
      "Debugging techniques",
      "Best coding practices",
    ],
    courseFeatures: [
      "Beginner-friendly approach",
      "Hands-on coding practice",
      "Step-by-step guidance",
      "Real programming challenges",
      "Code optimization techniques",
      "Industry-standard practices",
      "Comprehensive exercises",
      "Mentor support",
    ],
    salaryStatistics: [
      {
        title: "Average Salary in India",
        lpa: "₹7.8 LPA",
        subtitle: "Based on current market data",
      },
      {
        title: "Top Earners (90th percentile)",
        lpa: "₹18+ LPA",
        subtitle: "Experienced professionals",
      },
      {
        title: "Entry Level Range",
        lpa: "₹3-4.5 LPA",
        subtitle: "Fresh graduates",
      },
    ],
    marketInsights: [
      {
        title: "Industry Size",
        content: "$68.4 billion",
        subtitle: "Expected market size by 2025",
      },
      {
        title: "Job Growth Rate",
        content: "15%",
        subtitle: "Steady growth rate",
      },
      {
        title: "Remote Work",
        content: "55%",
        subtitle: "Positions offer remote work",
      },
    ],
    hiringCompanies: [
      "Intel",
      "Qualcomm",
      "Broadcom",
      "TI",
      "Bosch",
      "Continental",
      "Honeywell",
      "Siemens",
      "IBM",
      "HP",
    ],
  },
  {
    courseId: 4,
    courseName: "Flutter",
    courseIcon: "🦋",
    courseImg: "https://example.com/flutter-course.jpg",
    description:
      "Build beautiful, natively compiled mobile applications for iOS and Android using Google's Flutter framework.",
    duration: "3-4 months",
    students: 12850,
    rating: 4.7,
    level: "Intermediate",
    price: "₹28,999",
    avgSalary: {
      fresher: "₹5 LPA",
      experienced: "₹14 LPA",
      average: "₹9.5 LPA",
    },
    availability: {
      online: true,
      offline: true,
      hybrid: true,
    },
    completionRate: 82,
    growthData: [
      { year: 2020, demand: 45, salary: 580000 },
      { year: 2021, demand: 62, salary: 680000 },
      { year: 2022, demand: 78, salary: 780000 },
      { year: 2023, demand: 89, salary: 880000 },
      { year: 2024, demand: 95, salary: 950000 },
    ],
    salaryByExperience: [
      { experience: "0-1 years", salary: 500000 },
      { experience: "1-3 years", salary: 750000 },
      { experience: "3-5 years", salary: 1100000 },
      { experience: "5-8 years", salary: 1600000 },
      { experience: "8+ years", salary: 2200000 },
    ],
    careerPaths: [
      {
        title: "Mobile App Developer",
        growth: "Very High",
        salary: "₹6-12 LPA",
      },
      { title: "Flutter Developer", growth: "Very High", salary: "₹8-16 LPA" },
      { title: "Full Stack Developer", growth: "High", salary: "₹10-18 LPA" },
      { title: "Mobile Architect", growth: "Medium", salary: "₹18-30 LPA" },
    ],
    whatYouLearn: [
      "Flutter framework fundamentals",
      "Dart programming language",
      "Widget architecture",
      "State management (Provider, Bloc)",
      "Navigation and routing",
      "API integration and HTTP",
      "Local storage and databases",
      "Firebase integration",
      "App deployment (Play Store, App Store)",
      "Performance optimization",
    ],
    courseFeatures: [
      "Latest Flutter version",
      "Real app development projects",
      "iOS and Android deployment",
      "Industry mentor guidance",
      "Live coding sessions",
      "Portfolio development",
      "App store publishing guide",
      "Job placement assistance",
    ],
    salaryStatistics: [
      {
        title: "Average Salary in India",
        lpa: "₹9.5 LPA",
        subtitle: "Based on current market data",
      },
      {
        title: "Top Earners (90th percentile)",
        lpa: "₹22+ LPA",
        subtitle: "Experienced professionals",
      },
      {
        title: "Entry Level Range",
        lpa: "₹4.5-6 LPA",
        subtitle: "Fresh graduates",
      },
    ],
    marketInsights: [
      {
        title: "Industry Size",
        content: "$156.5 billion",
        subtitle: "Expected market size by 2025",
      },
      {
        title: "Job Growth Rate",
        content: "28%",
        subtitle: "Fastest growing segment",
      },
      {
        title: "Remote Work",
        content: "82%",
        subtitle: "Positions offer remote work",
      },
    ],
    hiringCompanies: [
      "Google",
      "Alibaba",
      "BMW",
      "Tencent",
      "Nubank",
      "Groupon",
      "Reflectly",
      "Hamilton",
      "Philips Hue",
      "Grab",
    ],
  },
  {
    courseId: 5,
    courseName: "Frontend Development",
    courseIcon: "🎨",
    courseImg: "https://example.com/frontend-course.jpg",
    description:
      "Master modern frontend technologies including HTML5, CSS3, JavaScript, and popular frameworks for responsive web development.",
    duration: "4-5 months",
    students: 28750,
    rating: 4.5,
    level: "Beginner to Intermediate",
    price: "₹22,999",
    avgSalary: {
      fresher: "₹4.2 LPA",
      experienced: "₹12 LPA",
      average: "₹8.1 LPA",
    },
    availability: {
      online: true,
      offline: true,
      hybrid: true,
    },
    completionRate: 79,
    growthData: [
      { year: 2020, demand: 68, salary: 520000 },
      { year: 2021, demand: 75, salary: 590000 },
      { year: 2022, demand: 82, salary: 660000 },
      { year: 2023, demand: 88, salary: 730000 },
      { year: 2024, demand: 94, salary: 810000 },
    ],
    salaryByExperience: [
      { experience: "0-1 years", salary: 420000 },
      { experience: "1-3 years", salary: 620000 },
      { experience: "3-5 years", salary: 920000 },
      { experience: "5-8 years", salary: 1400000 },
      { experience: "8+ years", salary: 1900000 },
    ],
    careerPaths: [
      { title: "Frontend Developer", growth: "Very High", salary: "₹5-12 LPA" },
      { title: "UI Developer", growth: "High", salary: "₹6-14 LPA" },
      { title: "Web Developer", growth: "High", salary: "₹4-10 LPA" },
      { title: "Frontend Architect", growth: "Medium", salary: "₹15-25 LPA" },
    ],
    whatYouLearn: [
      "HTML5 and semantic markup",
      "CSS3 and advanced styling",
      "JavaScript ES6+ features",
      "Responsive web design",
      "CSS frameworks (Bootstrap, Tailwind)",
      "Version control with Git",
      "Build tools and bundlers",
      "Frontend frameworks overview",
      "Performance optimization",
      "Cross-browser compatibility",
    ],
    courseFeatures: [
      "Project-based learning",
      "Industry-relevant curriculum",
      "Live coding sessions",
      "Portfolio development",
      "Responsive design focus",
      "Modern tools and workflows",
      "Code review and feedback",
      "Career preparation",
    ],
    salaryStatistics: [
      {
        title: "Average Salary in India",
        lpa: "₹8.1 LPA",
        subtitle: "Based on current market data",
      },
      {
        title: "Top Earners (90th percentile)",
        lpa: "₹19+ LPA",
        subtitle: "Experienced professionals",
      },
      {
        title: "Entry Level Range",
        lpa: "₹3.5-5 LPA",
        subtitle: "Fresh graduates",
      },
    ],
    marketInsights: [
      {
        title: "Industry Size",
        content: "$95.8 billion",
        subtitle: "Expected market size by 2025",
      },
      {
        title: "Job Growth Rate",
        content: "24%",
        subtitle: "Much faster than average",
      },
      {
        title: "Remote Work",
        content: "78%",
        subtitle: "Positions offer remote work",
      },
    ],
    hiringCompanies: [
      "Netflix",
      "Airbnb",
      "Spotify",
      "Uber",
      "Facebook",
      "Twitter",
      "LinkedIn",
      "Shopify",
      "Stripe",
      "Atlassian",
    ],
  },
  {
    courseId: 6,
    courseName: "Java",
    courseIcon: "☕",
    courseImg: "https://example.com/java-course.jpg",
    description:
      "Learn Java programming from fundamentals to advanced concepts including Spring framework and enterprise development.",
    duration: "5-6 months",
    students: 32450,
    rating: 4.4,
    level: "Beginner to Advanced",
    price: "₹24,999",
    avgSalary: {
      fresher: "₹4.5 LPA",
      experienced: "₹15 LPA",
      average: "₹9.8 LPA",
    },
    availability: {
      online: true,
      offline: true,
      hybrid: true,
    },
    completionRate: 76,
    growthData: [
      { year: 2020, demand: 72, salary: 580000 },
      { year: 2021, demand: 76, salary: 640000 },
      { year: 2022, demand: 80, salary: 700000 },
      { year: 2023, demand: 85, salary: 760000 },
      { year: 2024, demand: 89, salary: 820000 },
    ],
    salaryByExperience: [
      { experience: "0-1 years", salary: 450000 },
      { experience: "1-3 years", salary: 680000 },
      { experience: "3-5 years", salary: 1000000 },
      { experience: "5-8 years", salary: 1500000 },
      { experience: "8+ years", salary: 2100000 },
    ],
    careerPaths: [
      { title: "Java Developer", growth: "High", salary: "₹6-12 LPA" },
      { title: "Backend Developer", growth: "High", salary: "₹7-15 LPA" },
      {
        title: "Full Stack Developer",
        growth: "Very High",
        salary: "₹8-16 LPA",
      },
      { title: "Java Architect", growth: "Medium", salary: "₹18-30 LPA" },
    ],
    whatYouLearn: [
      "Java fundamentals and OOP",
      "Collections and generics",
      "Exception handling",
      "Multithreading and concurrency",
      "JDBC and database connectivity",
      "Spring framework basics",
      "Spring Boot development",
      "RESTful web services",
      "Testing with JUnit",
      "Build tools (Maven, Gradle)",
    ],
    courseFeatures: [
      "Comprehensive Java curriculum",
      "Real-world project development",
      "Industry-standard frameworks",
      "Expert instructor guidance",
      "Live coding demonstrations",
      "Code review sessions",
      "Interview preparation",
      "Job placement support",
    ],
    salaryStatistics: [
      {
        title: "Average Salary in India",
        lpa: "₹9.8 LPA",
        subtitle: "Based on current market data",
      },
      {
        title: "Top Earners (90th percentile)",
        lpa: "₹21+ LPA",
        subtitle: "Experienced professionals",
      },
      {
        title: "Entry Level Range",
        lpa: "₹4-6 LPA",
        subtitle: "Fresh graduates",
      },
    ],
    marketInsights: [
      {
        title: "Industry Size",
        content: "$108.7 billion",
        subtitle: "Expected market size by 2025",
      },
      {
        title: "Job Growth Rate",
        content: "20%",
        subtitle: "Faster than average growth",
      },
      {
        title: "Remote Work",
        content: "68%",
        subtitle: "Positions offer remote work",
      },
    ],
    hiringCompanies: [
      "Oracle",
      "IBM",
      "Accenture",
      "Capgemini",
      "TCS",
      "Infosys",
      "Wipro",
      "Amazon",
      "Microsoft",
      "Goldman Sachs",
    ],
  },
  {
    courseId: 7,
    courseName: "MEAN Stack",
    courseIcon: "🥞",
    courseImg: "https://example.com/mean-course.jpg",
    description:
      "Master full-stack development with MongoDB, Express.js, Angular, and Node.js for modern web applications.",
    duration: "5-6 months",
    students: 16420,
    rating: 4.6,
    level: "Intermediate to Advanced",
    price: "₹32,999",
    avgSalary: {
      fresher: "₹5.5 LPA",
      experienced: "₹16 LPA",
      average: "₹10.8 LPA",
    },
    availability: {
      online: true,
      offline: true,
      hybrid: true,
    },
    completionRate: 74,
    growthData: [
      { year: 2020, demand: 62, salary: 650000 },
      { year: 2021, demand: 70, salary: 720000 },
      { year: 2022, demand: 78, salary: 800000 },
      { year: 2023, demand: 86, salary: 880000 },
      { year: 2024, demand: 92, salary: 960000 },
    ],
    salaryByExperience: [
      { experience: "0-1 years", salary: 550000 },
      { experience: "1-3 years", salary: 800000 },
      { experience: "3-5 years", salary: 1200000 },
      { experience: "5-8 years", salary: 1700000 },
      { experience: "8+ years", salary: 2400000 },
    ],
    careerPaths: [
      {
        title: "MEAN Stack Developer",
        growth: "Very High",
        salary: "₹8-15 LPA",
      },
      {
        title: "Full Stack Developer",
        growth: "Very High",
        salary: "₹10-18 LPA",
      },
      { title: "Backend Developer", growth: "High", salary: "₹9-16 LPA" },
      { title: "Technical Lead", growth: "Medium", salary: "₹16-28 LPA" },
    ],
    whatYouLearn: [
      "MongoDB database design",
      "Express.js server development",
      "Angular frontend framework",
      "Node.js backend programming",
      "RESTful API development",
      "Authentication and authorization",
      "Real-time applications with Socket.io",
      "Testing strategies",
      "Deployment and DevOps",
      "Performance optimization",
    ],
    courseFeatures: [
      "Complete full-stack curriculum",
      "End-to-end project development",
      "Industry-relevant case studies",
      "Expert mentorship",
      "Live application deployment",
      "Code review and best practices",
      "Interview preparation",
      "Job placement assistance",
    ],
    salaryStatistics: [
      {
        title: "Average Salary in India",
        lpa: "₹10.8 LPA",
        subtitle: "Based on current market data",
      },
      {
        title: "Top Earners (90th percentile)",
        lpa: "₹24+ LPA",
        subtitle: "Experienced professionals",
      },
      {
        title: "Entry Level Range",
        lpa: "₹5-7 LPA",
        subtitle: "Fresh graduates",
      },
    ],
    marketInsights: [
      {
        title: "Industry Size",
        content: "$112.4 billion",
        subtitle: "Expected market size by 2025",
      },
      {
        title: "Job Growth Rate",
        content: "26%",
        subtitle: "Much faster than average",
      },
      {
        title: "Remote Work",
        content: "85%",
        subtitle: "Positions offer remote work",
      },
    ],
    hiringCompanies: [
      "Netflix",
      "Airbnb",
      "WhatsApp",
      "LinkedIn",
      "Upwork",
      "IBM",
      "Accenture",
      "Wipro",
      "TCS",
      "Infosys",
    ],
  },

  [
    {
      courseId: 1,
      courseName: "MERN Stack Development",
      courseIcon: "🚀",
      courseImg: "/images/mern-stack.jpg",
      description:
        "Master full-stack web development with MongoDB, Express.js, React.js, and Node.js. Build scalable, modern web applications from scratch.",
      duration: "6 months",
      students: 15420,
      rating: 4.8,
      level: "Intermediate",
      price: "₹45,000",
      avgSalary: {
        fresher: "₹4.5 LPA",
        experienced: "₹12 LPA",
        average: "₹7.5 LPA",
      },
      availability: {
        online: true,
        offline: true,
        hybrid: true,
      },
      completionRate: 87,
      growthData: [
        { year: 2020, demand: 65, salary: 450000 },
        { year: 2021, demand: 72, salary: 520000 },
        { year: 2022, demand: 78, salary: 600000 },
        { year: 2023, demand: 85, salary: 680000 },
        { year: 2024, demand: 92, salary: 750000 },
      ],
      salaryByExperience: [
        { experience: "0-1 years", salary: 450000 },
        { experience: "1-3 years", salary: 650000 },
        { experience: "3-5 years", salary: 950000 },
        { experience: "5+ years", salary: 1200000 },
      ],
      careerPaths: [
        { title: "Full Stack Developer", growth: "High", salary: "₹6-12 LPA" },
        { title: "React Developer", growth: "Very High", salary: "₹5-10 LPA" },
        { title: "Node.js Developer", growth: "High", salary: "₹6-11 LPA" },
        { title: "Technical Lead", growth: "High", salary: "₹12-18 LPA" },
      ],
      whatYouLearn: [
        "MongoDB database design and operations",
        "Express.js server-side development",
        "React.js frontend development",
        "Node.js backend programming",
        "RESTful API development",
        "Authentication and authorization",
        "State management with Redux",
        "Deployment and DevOps basics",
      ],
      courseFeatures: [
        "Live coding sessions",
        "Project-based learning",
        "Industry mentorship",
        "Career guidance",
        "Lifetime access to materials",
        "Certificate of completion",
        "Job placement assistance",
        "24/7 doubt support",
      ],
      salaryStatistics: [
        {
          title: "Average Salary in India",
          lpa: "₹7.5 LPA",
          subtitle: "Based on current market data",
        },
        {
          title: "Top Earners (90th percentile)",
          lpa: "₹15 LPA",
          subtitle: "Experienced professionals",
        },
        {
          title: "Entry Level Range",
          lpa: "₹4.5 LPA",
          subtitle: "Fresh graduates",
        },
      ],
      marketInsights: [
        {
          title: "Industry Size",
          content: "$180 billion",
          subtitle: "Expected market size by 2025",
        },
        {
          title: "Job Growth Rate",
          content: "22%",
          subtitle: "Faster than average growth",
        },
        {
          title: "Remote Work",
          content: "85%",
          subtitle: "Positions offer remote work",
        },
      ],
      hiringCompanies: [
        "Google",
        "Amazon",
        "Microsoft",
        "Meta",
        "Netflix",
        "Uber",
        "Airbnb",
        "Spotify",
        "Flipkart",
        "Swiggy",
        "Zomato",
        "Paytm",
        "PhonePe",
        "Byju's",
        "Unacademy",
      ],
    },
    {
      courseId: 2,
      courseName: "MySQL Database Administration",
      courseIcon: "🗄️",
      courseImg: "/images/mysql.jpg",
      description:
        "Master MySQL database management, optimization, and administration. Learn to design, implement, and maintain robust database systems.",
      duration: "4 months",
      students: 8950,
      rating: 4.6,
      level: "Intermediate",
      price: "₹25,000",
      avgSalary: {
        fresher: "₹4 LPA",
        experienced: "₹10 LPA",
        average: "₹6.5 LPA",
      },
      availability: {
        online: true,
        offline: true,
        hybrid: true,
      },
      completionRate: 85,
      growthData: [
        { year: 2020, demand: 70, salary: 400000 },
        { year: 2021, demand: 75, salary: 450000 },
        { year: 2022, demand: 78, salary: 520000 },
        { year: 2023, demand: 82, salary: 580000 },
        { year: 2024, demand: 85, salary: 650000 },
      ],
      salaryByExperience: [
        { experience: "0-1 years", salary: 400000 },
        { experience: "1-3 years", salary: 580000 },
        { experience: "3-5 years", salary: 800000 },
        { experience: "5+ years", salary: 1000000 },
      ],
      careerPaths: [
        {
          title: "Database Administrator",
          growth: "High",
          salary: "₹6-12 LPA",
        },
        { title: "Database Developer", growth: "Medium", salary: "₹5-9 LPA" },
        { title: "Data Architect", growth: "High", salary: "₹8-15 LPA" },
        { title: "Backend Developer", growth: "High", salary: "₹6-11 LPA" },
      ],
      whatYouLearn: [
        "MySQL installation and configuration",
        "Database design and normalization",
        "SQL query optimization",
        "Backup and recovery strategies",
        "Performance tuning and monitoring",
        "Security best practices",
        "Replication and clustering",
        "Stored procedures and functions",
      ],
      courseFeatures: [
        "Hands-on lab sessions",
        "Real-world database projects",
        "Performance optimization techniques",
        "Industry-standard tools",
        "Certificate of completion",
        "Job placement support",
        "Expert mentorship",
        "Flexible learning schedule",
      ],
      salaryStatistics: [
        {
          title: "Average Salary in India",
          lpa: "₹6.5 LPA",
          subtitle: "Based on current market data",
        },
        {
          title: "Top Earners (90th percentile)",
          lpa: "₹12 LPA",
          subtitle: "Experienced professionals",
        },
        {
          title: "Entry Level Range",
          lpa: "₹4 LPA",
          subtitle: "Fresh graduates",
        },
      ],
      marketInsights: [
        {
          title: "Industry Size",
          content: "$85 billion",
          subtitle: "Expected market size by 2025",
        },
        {
          title: "Job Growth Rate",
          content: "8%",
          subtitle: "Steady growth expected",
        },
        {
          title: "Remote Work",
          content: "70%",
          subtitle: "Positions offer remote work",
        },
      ],
      hiringCompanies: [
        "Oracle",
        "IBM",
        "Microsoft",
        "SAP",
        "TCS",
        "Infosys",
        "Wipro",
        "Cognizant",
        "Accenture",
        "Capgemini",
        "HCL",
        "Tech Mahindra",
        "Mindtree",
        "L&T Infotech",
        "Mphasis",
      ],
    },
    {
      courseId: 3,
      courseName: "React.js Development",
      courseIcon: "⚛️",
      courseImg: "/images/react.jpg",
      description:
        "Build dynamic, interactive user interfaces with React.js. Master modern frontend development with hooks, state management, and component architecture.",
      duration: "4 months",
      students: 18750,
      rating: 4.9,
      level: "Intermediate",
      price: "₹35,000",
      avgSalary: {
        fresher: "₹5 LPA",
        experienced: "₹13 LPA",
        average: "₹8 LPA",
      },
      availability: {
        online: true,
        offline: true,
        hybrid: true,
      },
      completionRate: 90,
      growthData: [
        { year: 2020, demand: 75, salary: 500000 },
        { year: 2021, demand: 82, salary: 580000 },
        { year: 2022, demand: 88, salary: 680000 },
        { year: 2023, demand: 94, salary: 750000 },
        { year: 2024, demand: 98, salary: 800000 },
      ],
      salaryByExperience: [
        { experience: "0-1 years", salary: 500000 },
        { experience: "1-3 years", salary: 720000 },
        { experience: "3-5 years", salary: 1050000 },
        { experience: "5+ years", salary: 1300000 },
      ],
      careerPaths: [
        { title: "React Developer", growth: "Very High", salary: "₹6-13 LPA" },
        { title: "Frontend Developer", growth: "High", salary: "₹5-11 LPA" },
        { title: "UI Developer", growth: "High", salary: "₹5-10 LPA" },
        { title: "Frontend Architect", growth: "High", salary: "₹12-20 LPA" },
      ],
      whatYouLearn: [
        "React fundamentals and JSX",
        "Component lifecycle and hooks",
        "State management with Redux",
        "Routing with React Router",
        "Form handling and validation",
        "API integration and HTTP requests",
        "Testing with Jest and React Testing Library",
        "Performance optimization techniques",
      ],
      courseFeatures: [
        "Interactive coding exercises",
        "Real-world project portfolio",
        "Live code reviews",
        "Industry best practices",
        "Modern development tools",
        "Certificate of completion",
        "Job placement assistance",
        "Community support",
      ],
      salaryStatistics: [
        {
          title: "Average Salary in India",
          lpa: "₹8 LPA",
          subtitle: "Based on current market data",
        },
        {
          title: "Top Earners (90th percentile)",
          lpa: "₹16 LPA",
          subtitle: "Experienced professionals",
        },
        {
          title: "Entry Level Range",
          lpa: "₹5 LPA",
          subtitle: "Fresh graduates",
        },
      ],
      marketInsights: [
        {
          title: "Industry Size",
          content: "$120 billion",
          subtitle: "Expected market size by 2025",
        },
        {
          title: "Job Growth Rate",
          content: "25%",
          subtitle: "Faster than average growth",
        },
        {
          title: "Remote Work",
          content: "90%",
          subtitle: "Positions offer remote work",
        },
      ],
      hiringCompanies: [
        "Meta",
        "Netflix",
        "Airbnb",
        "Uber",
        "WhatsApp",
        "Instagram",
        "Dropbox",
        "Spotify",
        "Slack",
        "Flipkart",
        "Zomato",
        "Swiggy",
        "Paytm",
        "Razorpay",
        "Freshworks",
      ],
    },
    {
      courseId: 4,
      courseName: "UI/UX Design",
      courseIcon: "🎨",
      courseImg: "/images/ui-ux.jpg",
      description:
        "Create compelling user experiences and beautiful interfaces. Master design thinking, prototyping, and user research methodologies.",
      duration: "5 months",
      students: 12340,
      rating: 4.7,
      level: "Beginner",
      price: "₹40,000",
      avgSalary: {
        fresher: "₹4 LPA",
        experienced: "₹12 LPA",
        average: "₹7 LPA",
      },
      availability: {
        online: true,
        offline: true,
        hybrid: true,
      },
      completionRate: 82,
      growthData: [
        { year: 2020, demand: 68, salary: 400000 },
        { year: 2021, demand: 75, salary: 480000 },
        { year: 2022, demand: 82, salary: 580000 },
        { year: 2023, demand: 88, salary: 650000 },
        { year: 2024, demand: 92, salary: 700000 },
      ],
      salaryByExperience: [
        { experience: "0-1 years", salary: 400000 },
        { experience: "1-3 years", salary: 620000 },
        { experience: "3-5 years", salary: 900000 },
        { experience: "5+ years", salary: 1200000 },
      ],
      careerPaths: [
        { title: "UI Designer", growth: "High", salary: "₹5-10 LPA" },
        { title: "UX Designer", growth: "Very High", salary: "₹6-12 LPA" },
        { title: "Product Designer", growth: "High", salary: "₹7-15 LPA" },
        { title: "Design Lead", growth: "High", salary: "₹12-22 LPA" },
      ],
      whatYouLearn: [
        "Design thinking methodology",
        "User research and personas",
        "Wireframing and prototyping",
        "Visual design principles",
        "Figma and Adobe Creative Suite",
        "Interaction design patterns",
        "Usability testing methods",
        "Design system creation",
      ],
      courseFeatures: [
        "Design portfolio development",
        "Industry tools and software",
        "Real client projects",
        "Peer design reviews",
        "Mentorship from design leads",
        "Certificate of completion",
        "Job placement support",
        "Networking opportunities",
      ],
      salaryStatistics: [
        {
          title: "Average Salary in India",
          lpa: "₹7 LPA",
          subtitle: "Based on current market data",
        },
        {
          title: "Top Earners (90th percentile)",
          lpa: "₹15 LPA",
          subtitle: "Experienced professionals",
        },
        {
          title: "Entry Level Range",
          lpa: "₹4 LPA",
          subtitle: "Fresh graduates",
        },
      ],
      marketInsights: [
        {
          title: "Industry Size",
          content: "$95 billion",
          subtitle: "Expected market size by 2025",
        },
        {
          title: "Job Growth Rate",
          content: "13%",
          subtitle: "Much faster than average",
        },
        {
          title: "Remote Work",
          content: "85%",
          subtitle: "Positions offer remote work",
        },
      ],
      hiringCompanies: [
        "Google",
        "Apple",
        "Microsoft",
        "Adobe",
        "Figma",
        "Canva",
        "Zomato",
        "Swiggy",
        "Flipkart",
        "Paytm",
        "Ola",
        "Uber",
        "Airbnb",
        "Spotify",
        "Netflix",
      ],
    },
    {
      courseId: 5,
      courseName: "Data Analytics",
      courseIcon: "📊",
      courseImg: "/images/data-analytics.jpg",
      description:
        "Transform raw data into actionable insights. Master statistical analysis, data visualization, and business intelligence tools.",
      duration: "6 months",
      students: 14580,
      rating: 4.8,
      level: "Intermediate",
      price: "₹50,000",
      avgSalary: {
        fresher: "₹5 LPA",
        experienced: "₹15 LPA",
        average: "₹8.5 LPA",
      },
      availability: {
        online: true,
        offline: true,
        hybrid: true,
      },
      completionRate: 88,
      growthData: [
        { year: 2020, demand: 78, salary: 500000 },
        { year: 2021, demand: 85, salary: 600000 },
        { year: 2022, demand: 92, salary: 720000 },
        { year: 2023, demand: 96, salary: 800000 },
        { year: 2024, demand: 98, salary: 850000 },
      ],
      salaryByExperience: [
        { experience: "0-1 years", salary: 500000 },
        { experience: "1-3 years", salary: 750000 },
        { experience: "3-5 years", salary: 1100000 },
        { experience: "5+ years", salary: 1500000 },
      ],
      careerPaths: [
        { title: "Data Analyst", growth: "Very High", salary: "₹6-12 LPA" },
        { title: "Business Analyst", growth: "High", salary: "₹7-14 LPA" },
        { title: "Data Scientist", growth: "Very High", salary: "₹8-18 LPA" },
        { title: "Analytics Manager", growth: "High", salary: "₹12-25 LPA" },
      ],
      whatYouLearn: [
        "Statistical analysis and probability",
        "Data cleaning and preprocessing",
        "SQL for data manipulation",
        "Python/R for data analysis",
        "Data visualization with Tableau/Power BI",
        "Machine learning basics",
        "Business intelligence concepts",
        "A/B testing and experimentation",
      ],
      courseFeatures: [
        "Real-world datasets",
        "Industry case studies",
        "Interactive dashboards",
        "Statistical software training",
        "Capstone project",
        "Certificate of completion",
        "Job placement assistance",
        "Ongoing mentorship",
      ],
      salaryStatistics: [
        {
          title: "Average Salary in India",
          lpa: "₹8.5 LPA",
          subtitle: "Based on current market data",
        },
        {
          title: "Top Earners (90th percentile)",
          lpa: "₹18 LPA",
          subtitle: "Experienced professionals",
        },
        {
          title: "Entry Level Range",
          lpa: "₹5 LPA",
          subtitle: "Fresh graduates",
        },
      ],
      marketInsights: [
        {
          title: "Industry Size",
          content: "$274 billion",
          subtitle: "Expected market size by 2025",
        },
        {
          title: "Job Growth Rate",
          content: "31%",
          subtitle: "Much faster than average",
        },
        {
          title: "Remote Work",
          content: "75%",
          subtitle: "Positions offer remote work",
        },
      ],
      hiringCompanies: [
        "Google",
        "Amazon",
        "Microsoft",
        "IBM",
        "Accenture",
        "McKinsey",
        "Deloitte",
        "PwC",
        "EY",
        "Flipkart",
        "Ola",
        "Zomato",
        "Paytm",
        "Swiggy",
        "Byju's",
      ],
    },
    {
      courseId: 6,
      courseName: "Java Full Stack Development",
      courseIcon: "☕",
      courseImg: "/images/java-fullstack.jpg",
      description:
        "Build enterprise-grade applications with Java. Master Spring Framework, microservices, and full-stack development with React frontend.",
      duration: "7 months",
      students: 16780,
      rating: 4.7,
      level: "Intermediate",
      price: "₹55,000",
      avgSalary: {
        fresher: "₹5.5 LPA",
        experienced: "₹14 LPA",
        average: "₹8.5 LPA",
      },
      availability: {
        online: true,
        offline: true,
        hybrid: true,
      },
      completionRate: 85,
      growthData: [
        { year: 2020, demand: 85, salary: 550000 },
        { year: 2021, demand: 88, salary: 620000 },
        { year: 2022, demand: 90, salary: 720000 },
        { year: 2023, demand: 92, salary: 800000 },
        { year: 2024, demand: 94, salary: 850000 },
      ],
      salaryByExperience: [
        { experience: "0-1 years", salary: 550000 },
        { experience: "1-3 years", salary: 780000 },
        { experience: "3-5 years", salary: 1150000 },
        { experience: "5+ years", salary: 1400000 },
      ],
      careerPaths: [
        { title: "Java Developer", growth: "High", salary: "₹6-12 LPA" },
        { title: "Full Stack Developer", growth: "High", salary: "₹7-14 LPA" },
        {
          title: "Spring Boot Developer",
          growth: "Very High",
          salary: "₹8-15 LPA",
        },
        { title: "Solution Architect", growth: "High", salary: "₹15-25 LPA" },
      ],
      whatYouLearn: [
        "Core Java and OOP concepts",
        "Spring Framework and Spring Boot",
        "Hibernate and JPA",
        "RESTful web services",
        "Microservices architecture",
        "React.js frontend development",
        "Database design and SQL",
        "DevOps and deployment",
      ],
      courseFeatures: [
        "Enterprise project development",
        "Industry-standard frameworks",
        "Code review sessions",
        "Agile methodology training",
        "Mock interviews",
        "Certificate of completion",
        "Job placement support",
        "Alumni network access",
      ],
      salaryStatistics: [
        {
          title: "Average Salary in India",
          lpa: "₹8.5 LPA",
          subtitle: "Based on current market data",
        },
        {
          title: "Top Earners (90th percentile)",
          lpa: "₹17 LPA",
          subtitle: "Experienced professionals",
        },
        {
          title: "Entry Level Range",
          lpa: "₹5.5 LPA",
          subtitle: "Fresh graduates",
        },
      ],
      marketInsights: [
        {
          title: "Industry Size",
          content: "$200 billion",
          subtitle: "Expected market size by 2025",
        },
        {
          title: "Job Growth Rate",
          content: "19%",
          subtitle: "Much faster than average",
        },
        {
          title: "Remote Work",
          content: "80%",
          subtitle: "Positions offer remote work",
        },
      ],
      hiringCompanies: [
        "Oracle",
        "IBM",
        "TCS",
        "Infosys",
        "Wipro",
        "Cognizant",
        "Accenture",
        "Capgemini",
        "HCL",
        "Tech Mahindra",
        "L&T Infotech",
        "Mindtree",
        "Mphasis",
        "Hexaware",
        "Zensar",
      ],
    },
    {
      courseId: 7,
      courseName: "JavaScript Development",
      courseIcon: "🟨",
      courseImg: "/images/javascript.jpg",
      description:
        "Master the language of the web. Learn modern JavaScript, ES6+, DOM manipulation, and asynchronous programming for dynamic web applications.",
      duration: "4 months",
      students: 22150,
      rating: 4.8,
      level: "Beginner",
      price: "₹30,000",
      avgSalary: {
        fresher: "₹4.5 LPA",
        experienced: "₹11 LPA",
        average: "₹7 LPA",
      },
      availability: {
        online: true,
        offline: true,
        hybrid: true,
      },
      completionRate: 89,
      growthData: [
        { year: 2020, demand: 80, salary: 450000 },
        { year: 2021, demand: 85, salary: 520000 },
        { year: 2022, demand: 88, salary: 600000 },
        { year: 2023, demand: 92, salary: 660000 },
        { year: 2024, demand: 95, salary: 700000 },
      ],
      salaryByExperience: [
        { experience: "0-1 years", salary: 450000 },
        { experience: "1-3 years", salary: 650000 },
        { experience: "3-5 years", salary: 900000 },
        { experience: "5+ years", salary: 1100000 },
      ],
      careerPaths: [
        {
          title: "JavaScript Developer",
          growth: "Very High",
          salary: "₹5-10 LPA",
        },
        { title: "Frontend Developer", growth: "High", salary: "₹6-12 LPA" },
        { title: "Node.js Developer", growth: "High", salary: "₹6-11 LPA" },
        { title: "Full Stack Developer", growth: "High", salary: "₹7-13 LPA" },
      ],
      whatYouLearn: [
        "JavaScript fundamentals and ES6+",
        "DOM manipulation and events",
        "Asynchronous programming",
        "Ajax and Fetch API",
        "Modern development tools",
        "Error handling and debugging",
        "Browser APIs and storage",
        "Performance optimization",
      ],
      courseFeatures: [
        "Interactive coding challenges",
        "Real-world projects",
        "Live coding sessions",
        "Modern JavaScript features",
        "Browser compatibility",
        "Certificate of completion",
        "Job placement assistance",
        "Community support",
      ],
      salaryStatistics: [
        {
          title: "Average Salary in India",
          lpa: "₹7 LPA",
          subtitle: "Based on current market data",
        },
        {
          title: "Top Earners (90th percentile)",
          lpa: "₹14 LPA",
          subtitle: "Experienced professionals",
        },
        {
          title: "Entry Level Range",
          lpa: "₹4.5 LPA",
          subtitle: "Fresh graduates",
        },
      ],
      marketInsights: [
        {
          title: "Industry Size",
          content: "$150 billion",
          subtitle: "Expected market size by 2025",
        },
        {
          title: "Job Growth Rate",
          content: "24%",
          subtitle: "Much faster than average",
        },
        {
          title: "Remote Work",
          content: "88%",
          subtitle: "Positions offer remote work",
        },
      ],
      hiringCompanies: [
        "Google",
        "Microsoft",
        "Amazon",
        "Meta",
        "Apple",
        "Netflix",
        "Uber",
        "Airbnb",
        "Spotify",
        "Slack",
        "Flipkart",
        "Paytm",
        "Zomato",
        "Swiggy",
        "Ola",
      ],
    },
  ],
  [
    {
      courseId: 1,
      courseName: "Node.js Development",
      courseIcon: "🟢",
      courseImg: "nodejs-course.jpg",
      description:
        "Master server-side JavaScript development with Node.js. Build scalable backend applications, APIs, and microservices using the latest Node.js technologies and frameworks.",
      duration: "4-6 months",
      students: 12580,
      rating: 4.7,
      level: "Intermediate",
      price: "₹35,999",
      avgSalary: {
        fresher: "₹3.7 LPA",
        experienced: "₹17 LPA",
        average: "₹8.5 LPA",
      },
      availability: {
        online: true,
        offline: true,
        hybrid: true,
      },
      completionRate: 78,
      growthData: [
        { year: 2023, demand: 85, salary: 650000 },
        { year: 2024, demand: 92, salary: 750000 },
        { year: 2025, demand: 98, salary: 850000 },
      ],
      salaryByExperience: [
        { experience: "0-1 years", salary: 370000 },
        { experience: "2-4 years", salary: 680000 },
        { experience: "5-8 years", salary: 1200000 },
        { experience: "8+ years", salary: 1700000 },
      ],
      careerPaths: [
        { title: "Backend Developer", growth: "High", salary: "₹8-15 LPA" },
        {
          title: "Full Stack Developer",
          growth: "Very High",
          salary: "₹10-18 LPA",
        },
        { title: "DevOps Engineer", growth: "High", salary: "₹12-20 LPA" },
        { title: "Technical Lead", growth: "High", salary: "₹15-25 LPA" },
      ],
      whatYouLearn: [
        "Node.js fundamentals and core modules",
        "Express.js framework and middleware",
        "RESTful API development",
        "Database integration (MongoDB, PostgreSQL)",
        "Authentication and authorization",
        "Testing with Jest and Mocha",
        "Performance optimization",
        "Deployment and DevOps basics",
      ],
      courseFeatures: [
        "Real-world project portfolio",
        "Industry mentorship program",
        "Live coding sessions",
        "24/7 doubt resolution",
        "Job placement assistance",
        "Industry-recognized certification",
        "Cloud deployment training",
        "Microservices architecture",
      ],
      salaryStatistics: [
        {
          title: "Average Salary in India",
          lpa: "₹8.5 LPA",
          subtitle: "Based on current market data",
        },
        {
          title: "Top Earners (90th percentile)",
          lpa: "₹17+ LPA",
          subtitle: "Experienced professionals",
        },
        {
          title: "Entry Level Range",
          lpa: "₹3.7-5.5 LPA",
          subtitle: "Fresh graduates",
        },
      ],
      marketInsights: [
        {
          title: "Industry Size",
          content: "28% growth in job postings",
          subtitle: "Expected market size by 2025",
        },
        {
          title: "Job Growth Rate",
          content: "25% annually",
          subtitle: "Faster than average growth",
        },
        {
          title: "Remote Work",
          content: "85% of positions",
          subtitle: "Positions offer remote work",
        },
      ],
      hiringCompanies: [
        "Google",
        "Microsoft",
        "Amazon",
        "Netflix",
        "Uber",
        "Swiggy",
        "Zomato",
        "Flipkart",
        "Paytm",
        "BYJU'S",
        "Razorpay",
        "Freshworks",
        "Zoho",
        "InMobi",
        "Ola",
      ],
    },
    {
      courseId: 2,
      courseName: "Power BI Analytics",
      courseIcon: "📊",
      courseImg: "powerbi-course.jpg",
      description:
        "Transform raw data into actionable insights with Microsoft Power BI. Learn data visualization, dashboard creation, and business intelligence techniques.",
      duration: "3-4 months",
      students: 8940,
      rating: 4.6,
      level: "Beginner to Intermediate",
      price: "₹24,999",
      avgSalary: {
        fresher: "₹4.2 LPA",
        experienced: "₹15 LPA",
        average: "₹7.8 LPA",
      },
      availability: {
        online: true,
        offline: true,
        hybrid: true,
      },
      completionRate: 82,
      growthData: [
        { year: 2023, demand: 78, salary: 580000 },
        { year: 2024, demand: 88, salary: 680000 },
        { year: 2025, demand: 95, salary: 780000 },
      ],
      salaryByExperience: [
        { experience: "0-1 years", salary: 420000 },
        { experience: "2-4 years", salary: 650000 },
        { experience: "5-8 years", salary: 1100000 },
        { experience: "8+ years", salary: 1500000 },
      ],
      careerPaths: [
        {
          title: "Business Intelligence Analyst",
          growth: "High",
          salary: "₹6-12 LPA",
        },
        { title: "Data Analyst", growth: "Very High", salary: "₹7-14 LPA" },
        { title: "BI Developer", growth: "High", salary: "₹8-16 LPA" },
        {
          title: "Data Visualization Specialist",
          growth: "High",
          salary: "₹9-18 LPA",
        },
      ],
      whatYouLearn: [
        "Power BI Desktop and Service fundamentals",
        "Data modeling and transformation",
        "DAX (Data Analysis Expressions)",
        "Interactive dashboard creation",
        "Report building and sharing",
        "Power Query for data preparation",
        "Advanced visualizations",
        "Row-level security and governance",
      ],
      courseFeatures: [
        "Hands-on projects with real datasets",
        "Microsoft certification preparation",
        "Industry use case studies",
        "Expert instructor support",
        "Career guidance sessions",
        "Power BI certification exam voucher",
        "Cloud-based lab access",
        "Business storytelling with data",
      ],
      salaryStatistics: [
        {
          title: "Average Salary in India",
          lpa: "₹7.8 LPA",
          subtitle: "Based on current market data",
        },
        {
          title: "Top Earners (90th percentile)",
          lpa: "₹15+ LPA",
          subtitle: "Experienced professionals",
        },
        {
          title: "Entry Level Range",
          lpa: "₹4.2-6.5 LPA",
          subtitle: "Fresh graduates",
        },
      ],
      marketInsights: [
        {
          title: "Industry Size",
          content: "₹2.8 billion market",
          subtitle: "Expected market size by 2025",
        },
        {
          title: "Job Growth Rate",
          content: "22% annually",
          subtitle: "Faster than average growth",
        },
        {
          title: "Remote Work",
          content: "70% of positions",
          subtitle: "Positions offer remote work",
        },
      ],
      hiringCompanies: [
        "Microsoft",
        "Accenture",
        "Deloitte",
        "IBM",
        "TCS",
        "Infosys",
        "Wipro",
        "Capgemini",
        "EY",
        "KPMG",
        "PwC",
        "Cognizant",
        "HCL",
        "Tech Mahindra",
        "Mu Sigma",
      ],
    },
    {
      courseId: 3,
      courseName: "Python Programming",
      courseIcon: "🐍",
      courseImg: "python-course.jpg",
      description:
        "Learn Python programming from basics to advanced concepts. Master web development, data science, automation, and machine learning with Python.",
      duration: "4-5 months",
      students: 15240,
      rating: 4.8,
      level: "Beginner to Advanced",
      price: "₹29,999",
      avgSalary: {
        fresher: "₹3.2 LPA",
        experienced: "₹16 LPA",
        average: "₹9.1 LPA",
      },
      availability: {
        online: true,
        offline: true,
        hybrid: true,
      },
      completionRate: 85,
      growthData: [
        { year: 2023, demand: 90, salary: 720000 },
        { year: 2024, demand: 95, salary: 820000 },
        { year: 2025, demand: 98, salary: 910000 },
      ],
      salaryByExperience: [
        { experience: "0-1 years", salary: 320000 },
        { experience: "2-4 years", salary: 760000 },
        { experience: "5-8 years", salary: 1300000 },
        { experience: "8+ years", salary: 1600000 },
      ],
      careerPaths: [
        { title: "Python Developer", growth: "Very High", salary: "₹6-14 LPA" },
        {
          title: "Data Scientist",
          growth: "Extremely High",
          salary: "₹12-25 LPA",
        },
        {
          title: "Machine Learning Engineer",
          growth: "Very High",
          salary: "₹15-30 LPA",
        },
        { title: "Backend Developer", growth: "High", salary: "₹8-18 LPA" },
      ],
      whatYouLearn: [
        "Python syntax and fundamentals",
        "Object-oriented programming",
        "Web development with Django/Flask",
        "Data analysis with Pandas and NumPy",
        "Machine learning basics",
        "Database connectivity",
        "API development and integration",
        "Testing and debugging techniques",
      ],
      courseFeatures: [
        "Project-based learning approach",
        "AI/ML specialization tracks",
        "Industry expert mentorship",
        "GitHub portfolio development",
        "Coding interview preparation",
        "Python certification included",
        "Career transition support",
        "Live coding workshops",
      ],
      salaryStatistics: [
        {
          title: "Average Salary in India",
          lpa: "₹9.1 LPA",
          subtitle: "Based on current market data",
        },
        {
          title: "Top Earners (90th percentile)",
          lpa: "₹16+ LPA",
          subtitle: "Experienced professionals",
        },
        {
          title: "Entry Level Range",
          lpa: "₹3.2-5.8 LPA",
          subtitle: "Fresh graduates",
        },
      ],
      marketInsights: [
        {
          title: "Industry Size",
          content: "Most popular language",
          subtitle: "Expected market size by 2025",
        },
        {
          title: "Job Growth Rate",
          content: "30% annually",
          subtitle: "Faster than average growth",
        },
        {
          title: "Remote Work",
          content: "80% of positions",
          subtitle: "Positions offer remote work",
        },
      ],
      hiringCompanies: [
        "Google",
        "Amazon",
        "Microsoft",
        "Netflix",
        "Instagram",
        "Dropbox",
        "Spotify",
        "Uber",
        "TCS",
        "Infosys",
        "Wipro",
        "Accenture",
        "IBM",
        "Oracle",
        "Adobe",
      ],
    },
    {
      courseId: 4,
      courseName: "Python Full Stack Development",
      courseIcon: "🔥",
      courseImg: "python-fullstack-course.jpg",
      description:
        "Become a complete Python Full Stack Developer. Master both frontend and backend technologies including Django, React, databases, and cloud deployment.",
      duration: "6-8 months",
      students: 9870,
      rating: 4.9,
      level: "Intermediate to Advanced",
      price: "₹45,999",
      avgSalary: {
        fresher: "₹4.5 LPA",
        experienced: "₹20 LPA",
        average: "₹11.2 LPA",
      },
      availability: {
        online: true,
        offline: true,
        hybrid: true,
      },
      completionRate: 76,
      growthData: [
        { year: 2023, demand: 88, salary: 850000 },
        { year: 2024, demand: 93, salary: 980000 },
        { year: 2025, demand: 97, salary: 1120000 },
      ],
      salaryByExperience: [
        { experience: "0-1 years", salary: 450000 },
        { experience: "2-4 years", salary: 890000 },
        { experience: "5-8 years", salary: 1550000 },
        { experience: "8+ years", salary: 2000000 },
      ],
      careerPaths: [
        {
          title: "Full Stack Developer",
          growth: "Very High",
          salary: "₹8-18 LPA",
        },
        {
          title: "Senior Python Developer",
          growth: "High",
          salary: "₹12-22 LPA",
        },
        { title: "Tech Lead", growth: "High", salary: "₹18-35 LPA" },
        { title: "Solution Architect", growth: "High", salary: "₹25-45 LPA" },
      ],
      whatYouLearn: [
        "Advanced Python and Django framework",
        "React.js for frontend development",
        "RESTful API design and development",
        "Database design and optimization",
        "Authentication and security",
        "Cloud deployment (AWS/Azure)",
        "DevOps and CI/CD pipelines",
        "Testing and quality assurance",
      ],
      courseFeatures: [
        "End-to-end project development",
        "Industry-standard tech stack",
        "Capstone project portfolio",
        "1:1 mentorship sessions",
        "Job placement guarantee",
        "Full stack certification",
        "Cloud hosting credits included",
        "Interview preparation bootcamp",
      ],
      salaryStatistics: [
        {
          title: "Average Salary in India",
          lpa: "₹11.2 LPA",
          subtitle: "Based on current market data",
        },
        {
          title: "Top Earners (90th percentile)",
          lpa: "₹20+ LPA",
          subtitle: "Experienced professionals",
        },
        {
          title: "Entry Level Range",
          lpa: "₹4.5-7.5 LPA",
          subtitle: "Fresh graduates",
        },
      ],
      marketInsights: [
        {
          title: "Industry Size",
          content: "₹12.5 billion market",
          subtitle: "Expected market size by 2025",
        },
        {
          title: "Job Growth Rate",
          content: "35% annually",
          subtitle: "Faster than average growth",
        },
        {
          title: "Remote Work",
          content: "90% of positions",
          subtitle: "Positions offer remote work",
        },
      ],
      hiringCompanies: [
        "Meta",
        "Google",
        "Amazon",
        "Netflix",
        "Airbnb",
        "Uber",
        "Swiggy",
        "Zomato",
        "Flipkart",
        "Paytm",
        "BYJU'S",
        "Unacademy",
        "Ola",
        "PhonePe",
        "Razorpay",
      ],
    },
    {
      courseId: 5,
      courseName: "Selenium Automation Testing",
      courseIcon: "🔧",
      courseImg: "selenium-course.jpg",
      description:
        "Master automated testing with Selenium WebDriver. Learn to create robust test frameworks, perform cross-browser testing, and integrate with CI/CD pipelines.",
      duration: "3-4 months",
      students: 6450,
      rating: 4.5,
      level: "Beginner to Intermediate",
      price: "₹22,999",
      avgSalary: {
        fresher: "₹3.5 LPA",
        experienced: "₹12 LPA",
        average: "₹6.8 LPA",
      },
      availability: {
        online: true,
        offline: true,
        hybrid: true,
      },
      completionRate: 79,
      growthData: [
        { year: 2023, demand: 82, salary: 520000 },
        { year: 2024, demand: 87, salary: 600000 },
        { year: 2025, demand: 92, salary: 680000 },
      ],
      salaryByExperience: [
        { experience: "0-1 years", salary: 350000 },
        { experience: "2-4 years", salary: 580000 },
        { experience: "5-8 years", salary: 950000 },
        { experience: "8+ years", salary: 1200000 },
      ],
      careerPaths: [
        {
          title: "Automation Test Engineer",
          growth: "High",
          salary: "₹5-10 LPA",
        },
        { title: "QA Lead", growth: "High", salary: "₹8-15 LPA" },
        { title: "Test Architect", growth: "High", salary: "₹12-20 LPA" },
        { title: "DevOps Engineer", growth: "Very High", salary: "₹10-18 LPA" },
      ],
      whatYouLearn: [
        "Selenium WebDriver fundamentals",
        "Test framework design (TestNG/JUnit)",
        "Page Object Model implementation",
        "Cross-browser and parallel testing",
        "API testing integration",
        "CI/CD pipeline integration",
        "Performance testing basics",
        "Mobile automation with Appium",
      ],
      courseFeatures: [
        "Hands-on automation projects",
        "Industry-standard frameworks",
        "Real-world testing scenarios",
        "Expert QA mentorship",
        "Certification preparation",
        "Job placement support",
        "Tool integration training",
        "Agile testing methodologies",
      ],
      salaryStatistics: [
        {
          title: "Average Salary in India",
          lpa: "₹6.8 LPA",
          subtitle: "Based on current market data",
        },
        {
          title: "Top Earners (90th percentile)",
          lpa: "₹12+ LPA",
          subtitle: "Experienced professionals",
        },
        {
          title: "Entry Level Range",
          lpa: "₹3.5-5.2 LPA",
          subtitle: "Fresh graduates",
        },
      ],
      marketInsights: [
        {
          title: "Industry Size",
          content: "₹8.2 billion market",
          subtitle: "Expected market size by 2025",
        },
        {
          title: "Job Growth Rate",
          content: "20% annually",
          subtitle: "Faster than average growth",
        },
        {
          title: "Remote Work",
          content: "75% of positions",
          subtitle: "Positions offer remote work",
        },
      ],
      hiringCompanies: [
        "Accenture",
        "TCS",
        "Infosys",
        "Wipro",
        "Capgemini",
        "IBM",
        "Cognizant",
        "HCL",
        "Tech Mahindra",
        "Mindtree",
        "L&T Infotech",
        "Mphasis",
        "Hexaware",
        "Zensar",
        "NIIT",
      ],
    },
  ],
];
