import {
  ANGULAR_ICON,
  C_ICON,
  C_PLUS_ICON,
  FIGMA_ICON,
  FLUTTER_ICON,
  FRONTEND_ICON,
  JAVA_ICON,
  MEAN_ICON,
  MERN_ICON,
  MOBILE_DEV_ICON,
  MYSQL_ICON,
  REACT_ICON,
  WEB_ICON,
} from "../../../assets";
import type { CourseCardData } from "../../types";

export const courses: CourseCardData[] = [
  {
    courseImg: FRONTEND_ICON,
    courseName: "FRONTEND DEV",
    courseIcon: WEB_ICON,
    courseId: 1,
    description:
      "Master the art of building modern, responsive, and interactive websites using core technologies like HTML, CSS, JavaScript, and frameworks such as React and Angular. Learn UI/UX principles and create dynamic user experiences optimized for all devices.",
    rating: 4.8,
    duration: "3 Months",
    students: 1200,
    level: "Advanced",
    price: "₹16,000",
  },
  {
    courseImg: ANGULAR_ICON,
    courseName: "ANGULAR",
    courseIcon: WEB_ICON,
    courseId: 2,
    description:
      "Learn Angular, a powerful TypeScript-based framework developed by Google for building scalable and high-performance single-page applications. Explore component-driven architecture, routing, services, and state management in real-world projects.",
    rating: 4.7,
    duration: "2.5 Months",
    students: 950,
    level: "Intermediate",
    price: "₹10,000",
  },
  {
    courseImg: REACT_ICON,
    courseName: "REACT",
    courseIcon: MOBILE_DEV_ICON,
    courseId: 3,
    description:
      "Dive into React, the popular JavaScript library from Meta for building dynamic and component-based user interfaces. Understand virtual DOM, hooks, state management, and how to build high-performing web and mobile applications with ease.",
    rating: 4.9,
    duration: "2.5 Months",
    students: 1300,
    level: "Advanced",
    price: "₹8,000",
  },
  {
    courseImg: C_ICON,
    courseName: "C",
    courseIcon: MOBILE_DEV_ICON,
    courseId: 4,
    description:
      "Begin your programming journey with C, the foundational language for system software, embedded systems, and low-level development. Understand memory management, data structures, and write efficient, high-performance code.",
    rating: 4.6,
    duration: "2 Months",
    students: 1100,
    level: "Beginner",
    price: "₹12,000",
  },
  {
    courseImg: C_PLUS_ICON,
    courseName: "C++",
    courseIcon: MOBILE_DEV_ICON,
    courseId: 5,
    description:
      "Enhance your programming skills with C++, an object-oriented extension of C used in game development, competitive programming, and real-time systems. Learn about classes, inheritance, polymorphism, and STL (Standard Template Library).",
    rating: 4.7,
    duration: "2.5 Months",
    students: 980,
    level: "Intermediate",
    price: "₹12,000",
  },
  {
    courseImg: FIGMA_ICON,
    courseName: "FIGMA",
    courseIcon: MOBILE_DEV_ICON,
    courseId: 6,
    description:
      "Master UI/UX design using Figma, the industry-leading collaborative design tool. Learn how to create wireframes, prototypes, and design systems that bring your digital products to life with intuitive and accessible user experiences.",
    rating: 4.8,
    duration: "1.5 Months",
    students: 850,
    level: "Intermediate",
    price: "₹22,000",
  },
  {
    courseImg: JAVA_ICON,
    courseName: "JAVA",
    courseIcon: MOBILE_DEV_ICON,
    courseId: 7,
    description:
      "Learn Java, a versatile and object-oriented programming language used in enterprise systems, Android development, and backend APIs. Gain expertise in OOP principles, exception handling, multithreading, and build robust applications.",
    rating: 4.8,
    duration: "3 Months",
    students: 1150,
    level: "Intermediate",
    price: "₹16,000",
  },
  {
    courseImg: FLUTTER_ICON,
    courseName: "FLUTTER",
    courseIcon: MOBILE_DEV_ICON,
    courseId: 8,
    description:
      "Build beautiful, natively compiled mobile, web, and desktop apps using Flutter and Dart. Learn widget-based architecture, state management, and create cross-platform apps with a single codebase and smooth UI animations.",
    rating: 4.9,
    duration: "2.5 Months",
    students: 1250,
    level: "Advanced",
    price: "₹25,000",
  },
  {
    courseImg: MEAN_ICON,
    courseName: "MEAN STACK",
    courseIcon: MOBILE_DEV_ICON,
    courseId: 9,
    description:
      "Become a full-stack developer with the MEAN stack — MongoDB, Express.js, Angular, and Node.js. Learn how to develop complete web applications from backend APIs to dynamic frontends using a single JavaScript-based ecosystem.",
    rating: 4.8,
    duration: "4 Months",
    students: 1000,
    level: "Advanced",
    price: "₹32,000",
  },
  {
    courseImg: MERN_ICON,
    courseName: "MERN STACK",
    courseIcon: MOBILE_DEV_ICON,
    courseId: 10,
    description:
      "Master the MERN stack — MongoDB, Express.js, React, and Node.js — to build powerful full-stack web applications. Learn to create RESTful APIs, manage frontend and backend integration, and deploy production-ready apps.",
    rating: 4.9,
    duration: "4 Months",
    students: 1400,
    level: "Advanced",
    price: "₹32,000",
  },
  {
    courseImg: MYSQL_ICON,
    courseName: "MYSQL",
    courseIcon: MOBILE_DEV_ICON,
    courseId: 11,
    description:
      "Learn MySQL, one of the most popular relational database management systems used worldwide. Understand how to design schemas, write complex SQL queries, and manage structured data efficiently for any application.",
    rating: 4.7,
    duration: "2 Months",
    students: 1050,
    level: "Intermediate",
    price: "₹8,000",
  },
];

